### PR TITLE
Git assistant testing

### PR DESCRIPTION
**Pull request by frosty1313**
Rewrote:
nmap to use python nmap, now returns a dict of results and writes to scan_results.json
spopen to use tempfiles for output to prevent memory exhaustion
start_grr to not require user action
configure_grr to use regexes internally and not require user action, although it currently sleeps for 180 seconds to ensure completion
Added
log: a function that prints at different levels to the terminal
debug: a function that prints debugging information if prompted

### CODE REVIEW

**Comment by frosty1313** [comment]
**IM BAD AT GIT**

**Comment by mutedmouse** [comment]
Will merge tonight.

**Comment by frosty1313** [comment]
No rush, I made a mess of it

Robert Frost 
c: 512-413-3274

**Comment by mutedmouse** [comment]
I'll tap some grr initialize logic in tomorrow during a downtime

**Pull request merged**
